streamsurl = {
	# "Djam Radio": { 'url': "https://www.djamradio.com/actions/infos.php", 'parser': "djam_radio" },
	"FIP": { 'url': "https://www.fip.fr/livemeta/7", 'parser': "fip" },
	"FIP Nouveaute": { 'url': "https://www.fip.fr/livemeta/70", 'parser': "fip" },
	"FIP Reggae": { 'url': "https://www.fip.fr/livemeta/71", 'parser': "fip" },
	"FIP Electro": { 'url': "https://www.fip.fr/livemeta/74", 'parser': "fip" },
	"FIP Rock": { 'url': "https://www.fip.fr/livemeta/64", 'parser': "fip" },
	"FIP Jazz": { 'url': "https://www.fip.fr/livemeta/65", 'parser': "fip" },
	"FIP Groove": { 'url': "https://www.fip.fr/livemeta/66", 'parser': "fip" },
	"FIP Monde": { 'url': "https://www.fip.fr/livemeta/68", 'parser': "fip" },
	"France Culture": { 'url': "https://www.franceculture.fr/programmes?xmlHttpRequest=1", 'parser': "france_inter" },
	# "France Info": { 'url': "https://www.francetvinfo.fr/replay-radio/grille-des-emissions/", 'parser': "france_info" },
	"France Inter": { 'url': "https://www.franceinter.fr/programmes?xmlHttpRequest=1&ignoreGridHour=1", 'parser': "france_inter" },
	"France Musique": { 	'url': "https://www.francemusique.fr/programmes?xmlHttpRequest=1", 'parser': "france_inter" },
	# "Jazz Radio": { 'url': "http://www.jazzradio.fr/winradio/live.xml", 'parser': "Jazz_Radio" },
	# "Radio Classique": { 'url': "https://d3gf3bsqck8svl.cloudfront.net/direct-metadata/current.json", 'parser': "radio_classique" },
	# "Radio Meuh": { 'url': "http://player.radiomeuh.com/rtdata/tracks.json", 'parser': "radio_meuh" },
	# "Radio Nova": { 	'url': "http://www.nova.fr/radio/19577/player", 'parser': "radio_nova" },
	# "TSF Jazz": { 'url': "https://api.tsfjazz.com/api/tracklists/current/TSF?radio=TSF", 'parser': "tsf_jazz" },
	# "Voltage": { 'url': "https://www.voltage.fr/players/index/gettitrageplayer/idplayers/2174546520932614870", 'parser': "radio_fg" },
}
